name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    #Operating systems
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]

    steps:
    - uses: actions/checkout@v3
    
    #SSH key
    - uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    #Install dependencies
    - name: Install Linux Libraries
      if: runner.os == 'Linux'
      run : |
        sudo apt-get install libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    #Cmake (in Debug mode)
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_debug -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build_debug --config Debug

    - name: Run Tests
      working-directory: ${{github.workspace}}/build_debug
      run: ctest -C Debug --output-on-failure

